# provide a name if you wish
# name: btlz-test

networks:
  app-net:
    driver: bridge

volumes:
  postgres-vol:
    driver: local
  redis_queue-vol:
    driver: local

services:
  postgres:
    container_name: postgres

    image: postgres:16.1-alpine

    environment:
      # - PGPORT=${POSTGRES_PORT}
      # - POSTGRES_DB=${POSTGRES_DB}
      # - POSTGRES_USER=${POSTGRES_USER}
      # - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file: .env

    volumes:
      - postgres-vol:/var/lib/postgresql/data

    networks:
      - app-net

    expose:
      - ${POSTGRES_PORT}

    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped

  redis_queue:
    image: redis:7-alpine

    container_name: redis_queue

    restart: always

    volumes:
      - redis_queue-vol:/data:rw,z

    ports:
      - "6379:6379"

    expose:
      - 6379

    networks:
      - app-net

    command: ["redis-server"]

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  app:
    container_name: app

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PORT: ${APP_PORT}
      REDIS_HOST: redis_queue
      REDIS_PORT: ${REDIS_PORT}
      NODE_ENV: production
      ENDPOINT_TARIFF: ${ENDPOINT_TARIFF}
      API_KEY_WB: ${API_KEY_WB}
      SPREADSHEET_ID: ${SPREADSHEET_ID}
      CRON_PATTERN: ${CRON_PATTERN}

    ports:
      - ${APP_PORT}:${APP_PORT}

    depends_on:
      postgres:
        condition: service_healthy
      redis_queue:
        condition: service_healthy
    networks:
      - app-net

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5

    command: ["npm", "run", "start"]
    restart: unless-stopped
