services:
  app:
    env_file:
      - ./.env
      - ./.env.local

    volumes: []

    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      REDIS_HOST: redis_queue
      PORT: ${APP_PORT}
